import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Loading from "./loading";
import { Suspense } from "react";
import { ThemeProvider } from "@/context/ThemeContext";
import Header from "@/components/ui/Header";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Dialogue Room",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="transition-colors duration-300">
        <ThemeProvider>
          <ReduxProvider>
            <Suspense fallback={<Loading />}>
              <Toaster />
              <Header />
              {children}
            </Suspense>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
